-- MySQL Script generated by MySQL Workbench
-- Mon Oct 11 15:53:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mycv1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mycv1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mycv1` DEFAULT CHARACTER SET utf8 ;
USE `mycv1` ;

-- -----------------------------------------------------
-- Table `mycv1`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycv1`.`contact` (
  `contactId` INT NOT NULL AUTO_INCREMENT,
  `phoneNumber` VARCHAR(13) NULL,
  `email` VARCHAR(45) NOT NULL,
  `linkedin` VARCHAR(80) NULL,
  `skype` VARCHAR(80) NULL,
  PRIMARY KEY (`contactId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycv1`.`education` (
  `educationId` INT NOT NULL AUTO_INCREMENT,
  `bachelor` VARCHAR(80) NULL,
  `master` VARCHAR(80) NULL,
  `doctoral` VARCHAR(80) NULL,
  `languages` VARCHAR(150) NULL,
  `highSchool` VARCHAR(80) NULL,
  PRIMARY KEY (`educationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycv1`.`user` (
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `aboutMe` VARCHAR(200) NULL,
  `contactId` INT NOT NULL,
  `educationId` INT NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `contactId_idx` (`contactId` ASC) ,
  INDEX `educationId_idx` (`educationId` ASC),
  CONSTRAINT `contactId`
    FOREIGN KEY (`contactId`)
    REFERENCES `mycv1`.`contact` (`contactId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `educationId`
    FOREIGN KEY (`educationId`)
    REFERENCES `mycv1`.`education` (`educationId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycv1`.`experience` (
  `experienceId` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(80) NULL,
  `position` VARCHAR(80) NULL,
  `period` VARCHAR(80) NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`experienceId`),
  INDEX `userId_idx` (`username` ASC),
  CONSTRAINT `username`
    FOREIGN KEY (`username`)
    REFERENCES `mycv1`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
